apiVersion: v1
kind: Service
metadata:
    name: akskodey
    labels:
        app: akskodey
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: akskodey